package pojo;
// default package
// Generated 25 nov 2022 13:06:18 by Hibernate Tools 5.6.9.Final

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Animales generated by hbm2java
 */
@Entity
@Table(name = "animales")
public class Animal implements java.io.Serializable {

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Column(name = "nombre", unique = true, nullable = false, length = 40)
	private String nombre;
	
	@Column(name = "habitad",nullable = false, length = 40)
	private String habitad;
	
	@Column(name = "peso_aproximado",nullable = false, length = 10, precision = 2)
	private BigDecimal pesoAproximado;

	
	public Animal() {
	}

	public Animal(String nombre, String habitad, BigDecimal pesoAproximado) {
		this.nombre = nombre;
		this.habitad = habitad;
		this.pesoAproximado = pesoAproximado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getHabitad() {
		return this.habitad;
	}

	public void setHabitad(String habitad) {
		this.habitad = habitad;
	}

	public BigDecimal getPesoAproximado() {
		return this.pesoAproximado;
	}

	public void setPesoAproximado(BigDecimal pesoAproximado) {
		this.pesoAproximado = pesoAproximado;
	}

}
